# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman
[tools]
luau-lsp = "Quenty/luau-lsp@1.45.0-quenty"
moonwave-extractor = "UpliftGames/moonwave@1.3.0"
rojo = "quenty/rojo@7.5.0-quenty-npm-canary.3"
selene = "Kampfkarren/selene@0.28.0"
stylua = "johnnymorganz/stylua@2.1.0"
