/**
 * A node in the Rojo sourcemap tree (generated by `rojo sourcemap --absolute`).
 *
 * Each node represents a Roblox instance and optionally maps to one or more
 * filesystem paths.
 */
export interface SourcemapNode {
  name: string;
  className?: string;
  children?: SourcemapNode[];
  filePaths?: string[];
}
