name: "Lint PR"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v3.4.1
        with:
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}